### ISSUE TITLE
Vertaispalaute

### ISSUE THREAD

**Issue by JoakimJoensuu** [otahontas/javasynth#2]
# Vertaispalaute

Projekti kloonattu pe 30.8. klo 16:54.

## Hyvää

 - luokat jaoteltu pakkauksiin järkevästi, nimittäin luokan nimi yhdistettynä sen pakkauksen nimeen kertoo luokasta jo nimien perusteella paljon

 - käyttöohje näinkin simppelille ohjelmalle on hyvä, pelkällä sovelluksen käynnistämisellä saa tarpeellisen tiedon kuinka sovellusta käytetään

 - koodissa muuttujat ja metodien nimet kuvaavasti nimettyjä ja metodit sopivan lyhyitä

## Kehitettävää

Syötteellä `java -jar wavcompressor.jar  -lc 1.wav asd.wav` saan seuraavan tulostuksen:

    1072948
    Compression rate: 0.7349834843330644

Tuo `1072948` ei kerro hirveästi mitään.  
Myöskään en löydä mistään tuota pakattua tiedostoa asd.wav.
Buildattu .jar tiedosto ja .wav tiedosto olivat samassa kansiossa.

## Suorat ehdotukset

Käy muuttamassa CLIArgumentReader-luokasta kohdasta

        private static String usage =
        "Usage: java jar wavcompressor.jar [-opts] source dest\n"
        +"e.g. java jar wavcompressor.jar -lc orig.wav comp.wav\n"
        +"Opts:\n"
        +"-l Use LZW compression \t -h Use Huffman compression\n"
        +"-c Compress file \t -e Exctract file";

Kohta `jar` muotoon `-jar`. Mulla ei ainakaan käynnistyny, jos ei ollu viivaa siinä jar sanan edessä.

Jos argumentteja ei anneta tarpeeksi, esim source puuttuu, niin sille myös jokin virheilmoitus!

## Loppusanat 

Aluks harmitti että projektin aihe vaihtui, ois kiinnostanu nähä mitä aikasemmasta tulee. Mutta tääkin vaikuttaa myös mielenkiintoselta. 
Hyvään vauhtiin oot tän projektin saanu, vaikka kesken kaiken aihetta vaihdoit.

**Comment by otahontas** [comment]
Kiitos vielä hei kummastakin palautteista, ovat olleet hyviä ja tsemppaavia! Modasin näillä infoilla vielä käyttäjälle ohjelmaa vähän paremmaksi
